language: r

cache: packages

sudo: required

matrix:
  include:
    - os: linux
      r: release

r_packages:
  - data.table
  - devtools
  - covr


before_install:
  - sudo apt install r-cran-rjava
  - sudo R CMD javareconf

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

apt_packages:
 - openjdk-8-jre

