language: r

cache: packages

sudo: required

matrix:
  include:
    - os: linux
      r: release

r_packages:
  - data.table


before_install:
  - sudo apt-get install -y default-jre
  - sudo apt-get install -y default-jdk
  - sudo apt-get install r-cran-rjava

before_script:
  - sudo R CMD javareconf

warnings_are_errors: true
