language: r

cache: packages

sudo: required

matrix:
  include:
    - os: linux
      r: release

r_packages:
  - data.table
  - devtools
  - covr

apt_packages:
  - r-cran-rjava

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

